#!/bin/sh -e

OUT_DIR=out
TSC=node_modules/.bin/tsc

mkdir -p "$OUT_DIR/js"

./genKaitaiFsFiles.py "$OUT_DIR"

"$TSC" --outDir $OUT_DIR/js/ --noEmitOnError

cp -r \
	index.html \
	v2.html \
	sandbox.html \
	LICENSE-3RD-PARTY.txt \
	css \
	formats \
	samples \
	lib \
	"$OUT_DIR"

mkdir -p "$OUT_DIR/src/ui/Components"
cp -r src/ui/Components/*.html "$OUT_DIR/src/ui/Components"

mkdir -p "$OUT_DIR/src/ui/Parts"
cp -r src/ui/Parts/*.html "$OUT_DIR/src/ui/Parts"

./build.py "$OUT_DIR"