#!/bin/sh -e

OUT_DIR=out
TSC=node_modules/.bin/tsc

mkdir -p "$OUT_DIR/js"

./genKaitaiFsFiles.py "$OUT_DIR"

"$TSC" --outDir $OUT_DIR/js/ --noEmitOnError
echo '== js/config.js contents:'
cat out/js/config.js

cp -r \
	index.html \
	sandbox.html \
	css \
	formats \
	samples \
	lib \
	"$OUT_DIR"

./build.py "$OUT_DIR"